# Upload this to a D1 Mini device
# This imports receiver and transmitter functionality from other files
# Replace keys and passwords with your own values

esphome:
  name: ir-remote
  friendly_name: IR Remote
  on_boot:
    priority: -100
    then:
      - switch.turn_on: led_builtin

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "KEY_HERE"

ota:
  password: "PASSWORD_HERE"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ir-Remote Fallback Hotspot"
    password: "PW_HERE"

captive_portal:


# Since this switch gets imported by two sub-packages, we have to un-define one of them up here for it to compile
# Otherwise it complains about duplicate definitions
switch:
  - platform: gpio
    id: !remove led_builtin

packages:
  led-builtin: !include led-builtin-template.yaml
  ir-receiver: !include ir-receiver.yaml
  ir-transmitter: !include ir-transmitter.yaml
